### ISSUE TITLE
Couldn't find preset react-native-stage-0/decorator-support

### ISSUE THREAD

**Issue by shukerullah** [f0rr0/react-native-rating#1]
`
Couldn't find preset \"react-native-stage-0/decorator-support\" relative to directory \"/project_path/node_modules/react-native-rating\""
`

**Comment by f0rr0** [comment]
Can you paste the contents of your root `.babelrc` file here

**Comment by f0rr0** [comment]
@shukerullah should be fixed in `2.0.1`
